### ISSUE TITLE
How to test the code ?

### ISSUE THREAD

**Issue by madrainbo** [pavan2you/flutter-shopify#2]
Hi 
I tried downloading the code and going through it. However I see the main.dart file content is commented. 
Can you add some info to how to test/run the code locally

**Comment by praharshbhatt** [comment]
Hi pavan,
Can you please update us if this plugin is functional or not?

**Comment by pavan2you** [comment]
It is functional, due to the limited bandwidth we were using main.dart file as test suit for the various shopify methods. 

You can uncomment the necessary method calls to test. I can not commit anymore time in near future to better it. As it is open source, feel free to raise a pull request.
